spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nsm_db
    username: root
    password: zhujunheng2005
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.163.com
    port: 25
    username: zhujunheng2005@163.com
    password: BJHHTGGRWGIZDVMJ
    properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
                required: true
  data:
    redis:
      host: localhost
      port: 6379
      password: zhujunheng2005



minio:
  url: https://base.neusoftmedical.top
  accessKey: LN8872J8VVeUIXqtzhfs
  secretKey: O43xYEVQfj8DUgpT8Oqb6n7ZjiFGZeE0m9WWxqRE
  bucketName: nsm