spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nsm_db
    username: root
    password: zhujunheng2005
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: in-v3.mailjet.com
    port: 587
    username: f083a684d4b8baa0be5443c6a4aa42a2
    password: 81bd6c3cdcced7cdb48464b566efa4bb
    properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
                required: true
  data:
    redis:
      host: localhost
      port: 6379
      password: zhujunheng2005



minio:
  url: https://base.neusoftmedical.top
  accessKey: LN8872J8VVeUIXqtzhfs
  secretKey: O43xYEVQfj8DUgpT8Oqb6n7ZjiFGZeE0m9WWxqRE
  bucketName: nsm